[package]
name = "sunspot"
version = "0.0.0"
edition = "2021"
authors = ["Sammy Harris <sammy@stegabob.com>"]
description = "Coming soon"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
