[package]
name = "sunspot"
version = "0.0.0"
edition = "2021"
authors = ["Sammy Harris <sammy@stegabob.com>"]
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
